
services:
  jupyter:
    container_name: jupyter-webserver
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./vol/notebook:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="

  mssql-2022:
    container_name: devenv-mssql2k22
    build:
      context: .
      dockerfile: ./docker/mssql/Dockerfile
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"

  #for apache-airflow
  postgres:
      container_name: airflow-postgres
      image: postgres:9.6
      ports:
      - '5432:5432'
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
      logging:
          options:
              max-size: 10m
              max-file: "3"

  webserver:
      container_name: airflow-webserver
      image: puckel/docker-airflow:1.10.9
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
      logging:
          options:
              max-size: 10m
              max-file: "3"
      volumes:
          - ./vol/dags:/usr/local/airflow/dags
          # - ./dags:/usr/local/airflow/dags
          # - ./plugins:/usr/local/airflow/plugins
      ports:
          - "8080:8080"
      command: webserver
      healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3
